### ISSUE TITLE
Archetype Missing Dependency

### ISSUE THREAD

**Issue by jmcc0nn3ll** [cometd/cometd#1013]
Jetty-11

If you use the archetype to setup a cometd app, you can't deploy that resulting app to Jetty because it is missing the jetty-slf4j-impl inside the war file.

```
java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider org.eclipse.jetty.logging.JettyLoggingServiceProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:404)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:353)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:379)
	at org.eclipse.jetty.servlets.CrossOriginFilter.<clinit>(CrossOriginFilter.java:122)

```
This can be resolved with the following dependency in your pom.xml.

```
<dependency>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-slf4j-impl</artifactId>
  <version>${jetty-version}</version>
</dependency>
```

This seems fishy though, do we really want to rely on a specific container logging impl class like that in CometD?

**Comment by sbordet** [comment]
Closing as the issue was not a CometD issue.
