### ISSUE TITLE
Java WebSocket Jetty Client Latest version?

### ISSUE THREAD

**Issue by gmbett** [cometd/cometd#1188]
Hi, I'm bit confused about the versioning of your libraries

Is cometd-java-websocket-jetty-client library still being supported? (https://mvnrepository.com/artifact/org.cometd.java/cometd-java-websocket-jetty-client)

Is version 4.0.9 the latest one?

Thanks!

**Comment by sbordet** [comment]
> Hi, I'm bit confused about the versioning of your libraries

Have you read https://docs.cometd.org/current/reference/#_preface?

> Is cometd-java-websocket-jetty-client library still being supported?

Yes, although the artifact name is different starting from CometD 5.0.x, see https://docs.cometd.org/current/reference/#_migration_40_to_50.

**Comment by gmbett** [comment]
Thanks!

**Comment by gmbett** [comment]
Hey, I have another question... I'm currently using your webscoket library on an Android project, but now that I have updated the library to the latest version:

```
implementation 'org.cometd.java:cometd-java-client-websocket-jetty:7.0.5'
```

I get a crash when the WebSocketClient is created:

```
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/ServiceLoader$Provider;
        at org.eclipse.jetty.util.TypeUtil.serviceProviderStream(TypeUtil.java:801)
        at org.eclipse.jetty.util.TypeUtil.serviceStream(TypeUtil.java:788)
        at org.eclipse.jetty.websocket.core.WebSocketExtensionRegistry.<init>(WebSocketExtensionRegistry.java:33)
        at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:55)
        at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:49)
        at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:43)
        at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:67)
```

The project is already configured to use Java 11, so I'm not sure what's wrong here, any idea?

**Comment by gmbett** [comment]
Nevermind, I found the problem... I was thinking that java 11 was being used to compile the project but that was not the case, because of a configuration problem related to Ionic Capacitor.
