### ISSUE TITLE
NullPointerException in AbstractClientSession.getReleasableChannel

### ISSUE THREAD

**Issue by reid24** [cometd/cometd#1229]
**Cometd Version**
4.0.4
 
**Java Version**
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b31)
Java HotSpot(TM) Client VM (build 25.311-b31, mixed mode, sharing)
 
**Description**
 
Receive the following exception from our listener code.  We are running a pod in OCP that is connecting to Salesforce and listening for Platform Events.
This exception is always preceded by a 403 Unknown Client response on the handshake callout.
The exception happens intermittently, sometimes it can take several hours to appear.
Once the exception occurs, the listener no longer receives any Platform Event messages.
 
```
2022-07-13 12:27:46.328  INFO 9 --- [lient@5ed4bc-48] o.eclipse.jetty.client.ResponseNotifier  : Exception while notifying listener org.cometd.client.transport.LongPollingTransport$2@64f1775b
java.lang.NullPointerException: null
              at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
              at org.cometd.common.AbstractClientSession.getReleasableChannel(AbstractClientSession.java:336) ~[cometd-java-common-4.0.4.jar!/:4.0.4]
              at org.cometd.common.AbstractClientSession.receive(AbstractClientSession.java:254) ~[cometd-java-common-4.0.4.jar!/:4.0.4]
              at org.cometd.client.BayeuxClient.processMessage(BayeuxClient.java:798) ~[cometd-java-client-4.0.4.jar!/:4.0.4]
              at org.cometd.client.BayeuxClient.processMessages(BayeuxClient.java:621) ~[cometd-java-client-4.0.4.jar!/:4.0.4]
              at org.cometd.client.BayeuxClient.access$2000(BayeuxClient.java:101) ~[cometd-java-client-4.0.4.jar!/:4.0.4]
              at org.cometd.client.BayeuxClient$MessageTransportListener.onMessages(BayeuxClient.java:1260) ~[cometd-java-client-4.0.4.jar!/:4.0.4]
              at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:240) ~[cometd-java-client-4.0.4.jar!/:4.0.4]
              at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:374) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:597) ~[jetty-http-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1722) ~[jetty-http-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551) ~[jetty-http-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:208) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:148) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172) ~[jetty-client-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.46.v20220331.jar!/:9.4.46.v20220331]
              at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```
 
**How to reproduce?**
By connecting and reconnecting, consuming messages, for a period of several hours.

**Comment by sbordet** [comment]
This is the server sending to the client an unsuccessful `/meta/subscribe` message without the `subscription` field, which is a protocol error, as `/meta/subscribe` messages MUST contain the `subscription` field: https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe.

We can improve the error handling on the client, but this looks like a server problem, possibly caused by the client trying to subscribe to a wrong channel.

Also, we can fix this issue in CometD 5 and later, but CometD 4 is at End-Of-Life, see https://docs.cometd.org/current/reference/#_preface.

Also note that very soon, CometD 5 will be End-Of-Community-Support, see https://github.com/cometd/cometd/issues/1179.

**Comment by Ziauddin135** [comment]
Hi @reid24 ,

I am also facing this issue frequently for the 4.0.4 version. Please suggest if any solution or workaround 

Thanks

**Comment by sbordet** [comment]
Version 4.0.4 is obsolete, please upgrade.
See https://docs.cometd.org/current/reference/.

**Comment by Ziauddin135** [comment]
Hi @sbordet ,

how can i download all the dependencies for the latest version? can you help

Thanks

**Comment by sbordet** [comment]
> how can i download all the dependencies for the latest version?

This is typically done by build tools such as Maven or Gradle.

Please read the documentation at https://docs.cometd.org/current/reference/
