### ISSUE TITLE
NullPointerException while notifying listener org.cometd.client.transport.LongPollingTransport

### ISSUE THREAD

**Issue by shaipan** [cometd/cometd#1502]
Getting NullPointer Exception on CometD when Subscription to Salesforce platform event fails with 403:Unknown Client error.

```
11-Jul-2023 00:19:41.831 EDT INFO [pool-13-thread-33803] [org.apache.camel.component.salesforce.internal.streaming.SubscriptionHelper] [{}] - Subscribing to channel: /event/LMS_Event__e on endpoint: salesforce-UKG-SFConnection-PlatformEvent:///event/LMS_Event__e?bridgeErrorHandler=true ... 
11-Jul-2023 00:19:41.912 EDT INFO [SalesforceHttpClient@5d7fbc94-137] [org.eclipse.jetty.client.ResponseNotifier] [{}] - Exception while notifying listener org.cometd.client.transport.LongPollingTransport$2@1a6df628 
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_345]
	at org.cometd.common.AbstractClientSession.getReleasableChannel(AbstractClientSession.java:336) ~[cometd-java-common-4.0.4.jar:4.0.4]
	at org.cometd.common.AbstractClientSession.receive(AbstractClientSession.java:254) ~[cometd-java-common-4.0.4.jar:4.0.4]
	at org.cometd.client.BayeuxClient.processMessage(BayeuxClient.java:798) ~[cometd-java-client-4.0.4.jar:4.0.4]
	at org.cometd.client.BayeuxClient.processMessages(BayeuxClient.java:621) ~[cometd-java-client-4.0.4.jar:4.0.4]
	at org.cometd.client.BayeuxClient.access$2000(BayeuxClient.java:101) ~[cometd-java-client-4.0.4.jar:4.0.4]
	at org.cometd.client.BayeuxClient$MessageTransportListener.onMessages(BayeuxClient.java:1260) ~[cometd-java-client-4.0.4.jar:4.0.4]
	at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:240) ~[cometd-java-client-4.0.4.jar:4.0.4]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:365) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:591) [jetty-http-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1716) [jetty-http-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1545) [jetty-http-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:204) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:144) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172) [jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
11-Jul-2023 00:20:40.936 EDT WARN [pool-13-thread-33803] [org.apache.camel.component.salesforce.internal.streaming.SubscriptionHelper] [{}] - Connect failure: {failure={exception=java.io.EOFException: HttpConnectionOverHTTP@fd726ea::DecryptedEndPoint@a7ca193{l=/10.48.1.132:58868,r=ukgsf.my.salesforce.com/13.110.47.237:443,OPEN,fill=-,flush=-,to=59104/240000}, message={clientId=nky11gppow7tp626b81j1n4u9oyo, channel=/meta/connect, id=45244, connectionType=long-polling}, connectionType=long-polling}, channel=/meta/connect, id=45244, successful=false} 
```

**Comment by sbordet** [comment]
I'm sorry but unfortunately CometD 4.0.x is at end of life and not supported anymore.

You should try to contact Salesforce support and ask them to update the Camel integration.

**Comment by sbordet** [comment]
Closing as related to an EOL CometD version.
