### ISSUE TITLE
Handshake fails in CometD 8 on Tomcat 10

### ISSUE THREAD

**Issue by engelhjs** [cometd/cometd#1837]
**CometD version(s)**
8.0.2

**Java version & vendor** (use: `java -version`)
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

**Apache Tomcat version**
10.1.20

**Description**
When running CometD on Apache Tomcat 10 over HTTP (no websockets), the handshakre request fails with a 500 and `org.cometd.server.HttpException`.

Example POST request to `/cometd/handshake`

```json
[
  {
    "requestId": "tuhwdhpsvzigotjmrbqtxpcb",
    "id": "4",
    "version": "1.0",
    "minimumVersion": "1.0",
    "channel": "/meta/handshake",
    "supportedConnectionTypes": [
      "long-polling",
      "callback-polling"
    ],
    "advice": {
      "timeout": 60000,
      "interval": 0
    }
  }
]
```

Exception stack trace:

```
org.cometd.server.HttpException: java.lang.IllegalStateException: In non-blocking mode you may not write to the ServletOutputStream until the previous write has completed and isReady() returns true
	at org.cometd.server.http.AbstractHttpTransport$1.fail(AbstractHttpTransport.java:185)
	at org.cometd.server.http.AbstractHttpTransport$Writer.onCompleteFailure(AbstractHttpTransport.java:758)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:335)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:231)
	at org.cometd.server.http.AbstractHttpTransport.write(AbstractHttpTransport.java:213)
	at org.cometd.server.http.AbstractHttpTransport.flush(AbstractHttpTransport.java:437)
	at org.cometd.server.http.AbstractHttpTransport.lambda$processMessages$1(AbstractHttpTransport.java:244)
	at org.cometd.bayeux.Promise$3.succeed(Promise.java:119)
	at org.cometd.common.AsyncFoldLeft$AbstractLoop.run(AsyncFoldLeft.java:237)
	at org.cometd.common.AsyncFoldLeft.run(AsyncFoldLeft.java:107)
	at org.cometd.server.http.AbstractHttpTransport.processMessages(AbstractHttpTransport.java:242)
	at org.cometd.server.http.JSONHttpTransport.process(JSONHttpTransport.java:87)
	at org.cometd.server.http.JSONHttpTransport$UTF8Reader.finish(JSONHttpTransport.java:195)
	at org.cometd.server.http.JSONHttpTransport$UTF8Reader.onEOF(JSONHttpTransport.java:188)
	at org.cometd.server.http.JSONHttpTransport$AbstractReader.processEOF(JSONHttpTransport.java:156)
	at org.cometd.server.http.JSONHttpTransport$AbstractReader.onDataAvailable(JSONHttpTransport.java:140)
	at org.cometd.server.http.JSONHttpTransport$AbstractReader.read(JSONHttpTransport.java:107)
	at org.cometd.server.http.jakarta.JakartaCometDRequest$JakartaCometDInput.onDataAvailable(JakartaCometDRequest.java:159)
	at org.apache.coyote.Request.onDataAvailable(Request.java:272)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:204)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:243)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:50)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: In non-blocking mode you may not write to the ServletOutputStream until the previous write has completed and isReady() returns true
	at org.apache.catalina.connector.CoyoteOutputStream.checkNonBlockingWrite(CoyoteOutputStream.java:156)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:101)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:95)
	at org.cometd.server.http.jakarta.JakartaCometDResponse$JakartaCometDOutput.write(JakartaCometDResponse.java:89)
	at org.cometd.server.http.AbstractHttpTransport.writeBegin(AbstractHttpTransport.java:596)
	at org.cometd.server.http.AbstractHttpTransport$Writer.process(AbstractHttpTransport.java:703)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:250)
	... 26 more
```

**How to reproduce?**
I set up a minimal code example to reproduce here:
https://github.com/engelhjs/cometd-tomcat-10-test/tree/cometd-8.0.2
There is even no custom code, just web.xml configuration taken from the CometD manual.

This is the same example set up with CometD 7 and it works fine:
https://github.com/engelhjs/cometd-tomcat-10-test/tree/cometd-7.0.16

**Comment by sbordet** [comment]
I'm no Tomcat expert, but I think this is a Tomcat bug.

The problem is that Tomcat does not seem to allow writes unless they come from `onWritePossible()`.

In particular, this should be possible:

```java
void service(req, resp) {
  ServletOutputStream out = resp.getOutputStream();
  out.setWriteListener(new MyWriteListener());
  out.write(bytes);
}
```

This should be possible because the first write is obviously possible (nothing has been written yet, so obviously the output is ready to be written).

After the first write, this also should be possible:

```java
void service(req, resp) {
  ServletOutputStream out = resp.getOutputStream();
  out.setWriteListener(new MyWriteListener());
  out.write(bytes);
  if (out.isReady()) {
    out.write(moreBytes);
  }
}
```

I'll try to see if it is possible to work around easily this Tomcat bug, without complicating too much CometD code.

**Comment by sbordet** [comment]
I was able to work around this issue in https://github.com/cometd/cometd/pull/1838.

Can you try it out and report back if it fixes the problem for you?

**Comment by engelhjs** [comment]
Works perfectly well.
Thanks for the quick response!

**Comment by sbordet** [comment]
Thanks for the feedback!

**Comment by jtrentes** [comment]
We have exactly the same problem (Tomcat 10 and CometD 8.0.2). 
I tried the patch and it works for us too.

When do you plan to deploy the patch? Thanks!

**Comment by sbordet** [comment]
@jtrentes beginning next week.

**Comment by jtrentes** [comment]
@sbordet Thanks!

We also detected another problem after applying the patch. It seems that `BayeuxContext#getUserPrincipal` always returns null with JSONHttpTransport (it works fine with WebSocketTransport). Do you think this could be another similar bug?

**Comment by sbordet** [comment]
@jtrentes `BayeuxContext#getUserPrincipal` directly maps to `HttpServletRequest.getUserPrincipal()`, so it returns non-null if there is an authenticated user, that has been authenticated with the JEE means.

**Comment by jtrentes** [comment]
That's what I saw in the code, but I was asking just in case 👍
Thanks again.
