### ISSUE TITLE
Multicast Oort does not work on Windows

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#589]
Upton doing "mvn jetty:run" at cometd-demo on a fresh download of cometd-3.0.4 -

javax.servlet.ServletException: java.lang.IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group
	at org.cometd.oort.OortConfigServlet.init(OortConfigServlet.java:100)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:296)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:365)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357)
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by:
java.lang.IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group
	at sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:819)
	at sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:905)
	at org.cometd.oort.OortMulticastConfigurer.doStart(OortMulticastConfigurer.java:212)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.cometd.oort.OortMulticastConfigServlet.configureCloud(OortMulticastConfigServlet.java:121)
	at org.cometd.oort.OortConfigServlet.init(OortConfigServlet.java:84)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)

**Comment by sbordet** [comment]
It appears the same issue as https://issues.apache.org/jira/browse/HBASE-12359.

The fix for HBase is here: https://git-wip-us.apache.org/repos/asf?p=hbase.git;a=commit;h=0255fc2bf161741efbcddb1d5fa27c5f3ac95a45

**Comment by fallowu** [comment]
```
It appears the same issue as https://issues.apache.org/jira/browse/HBASE-12359.
The fix for HBase is here: https://git-wip-us.apache.org/repos/asf?p=hbase.git;a=commit;h=0255fc2bf161741efbcddb1d5fa27c5f3ac95a45
```
sorry for asking ,but how to deal with it as  beginner to test the cometd-demo and the version is 3.0.7?

**Comment by sbordet** [comment]
Investigated the issue. Turns out that Windows has a lot of network interfaces that are "enabled", support multicast, but are not actually bound to any IP address, so that `NetworkInterface.getInetAddresses()` returns an empty enumeration.

Calling `DatagramChannel.join()` with such network interfaces results in the reported error.

Also, the fix performed by HBase is also necessary to make sure that the correct `ProtocolFamily` is used.

**Comment by sbordet** [comment]
Fixed by using the correct `ProtocolFamily`, by skipping interfaces that have no addresses and by catching and ignoring exceptions while trying to join the multicast group.
