### ISSUE TITLE
AcknowledgedMessagesSessionExtension - java.lang.ArrayIndexOutOfBoundsException in BatchArrayQueue.clearToBatch

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#596]
When we have multiple notifications (about 300) send form server to client (2 different browsers) - then we spot that after sending some of them we see the ArrayIndexOutOfBounds exceptions in Java code:
{quote}
11:46:10,061 INFO  [org.cometd.bayeux.server.ServerSession](http-/0.0.0.0:8090-13) Exception while invoking listener org.cometd.server.ext.AcknowledgedMessagesSessionExtension@7d12b538: java.lang.ArrayIndexOutOfBoundsException: 16
    at org.cometd.server.ext.BatchArrayQueue.exportMessagesToBatch(BatchArrayQueue.java:159) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.ext.AcknowledgedMessagesSessionExtension.deQueue(AcknowledgedMessagesSessionExtension.java:127) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.ServerSessionImpl.notifyDeQueue(ServerSessionImpl.java:487) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.ServerSessionImpl.takeQueue(ServerSessionImpl.java:468) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.transport.AbstractHttpTransport.flush(AbstractHttpTransport.java:331) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.transport.AbstractHttpTransport.resume(AbstractHttpTransport.java:346) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.transport.AbstractStreamHttpTransport.process(AbstractStreamHttpTransport.java:82) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.transport.AbstractStreamHttpTransport.handle(AbstractStreamHttpTransport.java:52) [cometd-java-server-3.0.4.jar:]
    at org.cometd.server.CometDServlet.service(CometDServlet.java:102) [cometd-java-server-3.0.4.jar:]
{quote}

Please also see screen from debugger attached.

If you need more information don't hesitate to ask.

**Comment by sbordet** [comment]
No further information, not reproducible, closing.
