### ISSUE TITLE
LinkageError when using native Jetty WebSocket transport in webapp 

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#702]
When using the native Jetty WebSocket transport (not the JSR 356 transport), the following error is raised:

```
14:39:16.244|WARN |o.e.j.d.DeploymentManager||Unable to reach node goal: started
java.lang.LinkageError: loader constraint violation: when resolving method "org.eclipse.jetty.websocket.server.NativeWebSocketConfiguration.addMapping(Lorg/eclipse/jetty/http/pathmap/PathSpec;Lorg/eclipse/jetty/websocket/servlet/WebSocketCreator;)V" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/cometd/websocket/server/JettyWebSocketTransport, and the class loader (instance of org/eclipse/jetty/start/Classpath$Loader) for the method's defining class, org/eclipse/jetty/websocket/server/NativeWebSocketConfiguration, have different Class objects for the type org/eclipse/jetty/http/pathmap/PathSpec used in the signature
        at org.cometd.websocket.server.JettyWebSocketTransport.init(JettyWebSocketTransport.java:75)
        at org.cometd.server.BayeuxServerImpl.initializeServerTransports(BayeuxServerImpl.java:255)
        at org.cometd.server.BayeuxServerImpl.doStart(BayeuxServerImpl.java:135)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.cometd.server.CometDServlet.init(CometDServlet.java:64)
```

**Comment by sbordet** [comment]
Caused by eclipse/jetty.project#1229.
