### ISSUE TITLE
NoClassDefFoundError when running demo

### ISSUE THREAD

**Issue by ghuser** [cometd/cometd#757]
on 3.1.3  (apache-maven-3.5.0 / java: 1.8.0_151)

I  try to run: `mvn jetty:run -Djetty.http.port=9780` (inside cometd-demo)
and I get the following: 

WARNING] FAILED org.eclipse.jetty.io.SelectorManager$ManagedSelector@5ab319de keys=0 selected=0: java.lang.NoClassDefFoundError: org/eclipse/jetty/io/SelectorManager$ManagedSelector$Stop
java.lang.NoClassDefFoundError: org/eclipse/jetty/io/SelectorManager$ManagedSelector$Stop
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.doStop(SelectorManager.java:434)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:277)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
        at org.eclipse.jetty.websocket.client.io.ConnectionManager.doStop(ConnectionManager.java:217)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
        at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:279)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.doStop(ClientContainer.java:195)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)

**Comment by ghuser** [comment]
I used -X and saw that cause was that it could not bind to 8080. Problem was that I was using a deprecated property for jetty, so port change was not effective. I should have used `-Djetty.port=9780`. 

Of course it would be nice not to have ClassCastException in such a case, but I think its minor.
