### ISSUE TITLE
[4.0.0] NullPointerException in WebSocketTransport

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#791]
I updated to 4.0.0 (both the Java server and the JS client) and without too much changes in the code, I ran my project:

```
java.lang.NullPointerException: null
	at org.cometd.websocket.server.WebSocketTransport$WebSocketContext.<init>(WebSocketTransport.java:110)
	at org.cometd.websocket.server.WebSocketTransport$WebSocketContext.<init>(WebSocketTransport.java:102)
	at org.cometd.websocket.server.WebSocketTransport$Configurator.modifyHandshake(WebSocketTransport.java:133)
	at org.apache.tomcat.websocket.server.UpgradeUtil.doUpgrade(UpgradeUtil.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Tomcat/Shiro/CometD are at their latest versions. I have zero idea where this might come from. Suggestions?

**Comment by sbordet** [comment]
The line that NPEs does:

```
request.getRequestURI().getScheme().equalsIgnoreCase("https"));
```

The NPE should not happen since a request must exist, as well as an associated URI, and for that URI the scheme.

Can you try using Jetty instead of Tomcat?

**Comment by boris-petrov** [comment]
Trying Jetty would be a bit involved as we have some Tomcat-specific things. I'll take a look tomorrow.

Is it possible something to be modifying the request before that and removing some of these things? Shiro-web? Perhaps my own code (or is this before any of my code being hit)?

I'll debug it tomorrow and write what exactly is null in this line.

**Comment by boris-petrov** [comment]
OK, so the debugging showed that `request.getRequestURI()` returns a URI which is: `/project/streaming` and `getScheme()` on it returns `null` (which kind of makes sense). This comes from the websocket request from the FE: `ws://localhost:4200/project/streaming`. We use Ember CLI as a frontend build-pipeline and it actually proxies this request to our BE server which is at another port. I see in its logs: `Proxying websocket to /project/streaming`. Perhaps this is when the problem happens.

Do you think this is a problem in Ember CLI that they don't proxy using the full URL or an error in CometD that it doesn't handle that case? Note that this wasn't an issue in `3.1.5`.

**Comment by sbordet** [comment]
@boris-petrov that line retrieves whether the request has been made over a secure transport (a new feature in 4.0.0 - that's why works in 3.1.5), so IMHO it must be an absolute URI - this is because the JSR `HandshakeRequest` API does not give any other way to figure that out.

I can work it around by watching for NPEs and the like, but I think you should report this back to Tomcat.

**Comment by sbordet** [comment]
@boris-petrov I pushed a work-around for this issue, can you test if it works for you?
See https://docs.cometd.org/current4/reference/#_build to build CometD.

**Comment by boris-petrov** [comment]
I've opened a bug to Tomcat [here](https://bz.apache.org/bugzilla/show_bug.cgi?id=62731) - let's see what they'll say.

I'll try out master today or tomorrow, thanks for the support!

**Comment by sbordet** [comment]
@boris-petrov note that the branch to try is not `master` but `4.0.x`. The `master` branch is not used because we maintain multiple releases (3.1.x, 4.0.x, etc.) and explicit numbering on branch names helps knowing where exactly one is. Thanks!

**Comment by boris-petrov** [comment]
@sbordet - OK, this branch seems to fix that specific issue (or at least I think so, because of the following) but I'm getting a new exception now - `java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.Dumpable`. I see that this is used in a number of places in the code - but isn't this Jetty specific? If you think this is a real problem, perhaps we should open a new bug and leave this one open until we know for sure it is fixed.

**Comment by sbordet** [comment]
@boris-petrov please open a new issue about `Dumpable`.

**Comment by boris-petrov** [comment]
@sbordet - as I noted in the other issue, your fix works and our project works fine with it. Thank you for the support! I'll be expecting a 4.0.1 release then. :) I'll leave you to decide when to close this issue.
