### ISSUE TITLE
Throwing NPE is onTransportFailure() method.

### ISSUE THREAD

**Issue by punith619** [cometd/cometd#802]
Throwing NPE is onTransportFailure() method since transport is NULL and trying to get the name getTransport().getName() of the transport throws NPE.

 if (Message.RECONNECT_NONE_VALUE.equals(failureInfo.action)) {
            if (Channel.META_HANDSHAKE.equals(message.getChannel())) {
                if (failureInfo.transport == null) {
                    onTransportFailure(getTransport().getName(), null, failureInfo.cause);
                }
            }
   }

**Comment by sbordet** [comment]
`failureInfo.transport` and `getTransport()` may return two different transport instances, so the code does not throw a NPE.
Do you have a stack trace?

**Comment by punith619** [comment]
The client throwing NPE when the handshake fails if the host is unavailable (UnkownHostException)
Stacktrace:
java.lang.NullPointerException
     at org.cometd.client.BayeuxClient.onTransportFailure(BayeuxClient.java:1043)
     at org.cometd.client.BayeuxClient.failHandshake(BayeuxClient.java:742)
     at org.cometd.client.BayeuxClient.handshakeFailure(BayeuxClient.java:731)
     at org.cometd.client.BayeuxClient.messagesFailure(BayeuxClient.java:658)
     at org.cometd.client.BayeuxClient$MessageTransportListener.onFailure(BayeuxClient.java:1195)
     at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:214)
     at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
     at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
     at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
     at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
     at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
     at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:748)
     at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:447)
     at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:227)
     at org.eclipse.jetty.client.AbstractConnectionPool$1.failed(AbstractConnectionPool.java:124)
     at org.eclipse.jetty.client.HttpClient$1.failed(HttpClient.java:589)
     at org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:187)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)

**Comment by sbordet** [comment]
What CometD version?

**Comment by punith619** [comment]
Sorry, I forgot to mention. I am using v3.1.3.

**Comment by sbordet** [comment]
This has already been fixed by 921e0b9d2233e4357e393e1fb09bbb9f63303777 in 3.1.4.
