### ISSUE TITLE
NPE using WebsocketTransport with Undertow

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#806]
I'm getting an NPE when trying to integrate Undertow's JSR 356 support with CometD. 

In Undertow, `HandshakeRequest.getRequestURI()` returns just the path, not the full URL. This results in an NPE when seeing if the URI's scheme matches `https`:

```
ERROR [websocket-test-worker task-1] io.undertow.request {} - UT005023: Exception handling request to /foo/ws/cometd
java.lang.NullPointerException
	at org.cometd.websocket.server.WebSocketTransport$WebSocketContext.<init>(WebSocketTransport.java:110)
	at org.cometd.websocket.server.WebSocketTransport$WebSocketContext.<init>(WebSocketTransport.java:102)
	at org.cometd.websocket.server.WebSocketTransport$Configurator.modifyHandshake(WebSocketTransport.java:133)
	at io.undertow.websockets.jsr.handshake.HandshakeUtil.prepareUpgrade(HandshakeUtil.java:65)
	at io.undertow.websockets.jsr.handshake.JsrHybi13Handshake.upgradeChannel(JsrHybi13Handshake.java:53)
	at io.undertow.websockets.core.protocol.Handshake.performUpgrade(Handshake.java:124)
	at io.undertow.websockets.core.protocol.Handshake.performUpgrade(Handshake.java:152)
	at io.undertow.websockets.core.protocol.version13.Hybi13Handshake.handshakeInternal(Hybi13Handshake.java:66)
	at io.undertow.websockets.core.protocol.Handshake.handshake(Handshake.java:102)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:168)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
```

This seems to be a blocker without completely reimplementing WebsocketTransport to reverse the `equals` call, or do something different. I could also extend `AbstractWebsocketTransport` and use the native Undertow APIs.

Has anyone gotten this combination to work before? Should I submit a patch?

**Comment by nathklei** [comment]
Also of note, I couldn't figure out where the `secure` boolean was actually used in the websocket transport, so it could also just be defaulted to false.

**Comment by sbordet** [comment]
What CometD version are you using? 
The current 3.1.5 has (very) different line numbers with respect to the ones of your stack trace.
If you're not on 3.1.5, can you please upgrade and retry?

**Comment by nathklei** [comment]
@sbordet I'm on `4.0.0`

**Comment by nathklei** [comment]
Should I not use `4.0.0`? I'd been testing that version until now, but can go back down to `3.1.5` if you think this fixes the issue.

**Comment by nathklei** [comment]
Looking into this a bit more, it does seem like this new constructor arg was added in 4.0.0, so it would probably make sense to fix forward if possible rather than downgrade. I'm still in development, not in production. Let me know if you need more information!

**Comment by sbordet** [comment]
See #791.

It's already fixed in HEAD, would you be able to give HEAD a try to see if it works with Undertow?
I'll release 4.0.1 soon if you confirm.

**Comment by nathklei** [comment]
Sure, I can try that. Are those jars available anywhere? Or do I need to build+publish locally?

**Comment by sbordet** [comment]
I can quickly deploy them as SNAPSHOTs, available at https://oss.sonatype.org/content/repositories/snapshots/. That ok for you?

**Comment by nathklei** [comment]
I'm building locally at the moment, but in case that doesn't work, that would be helpful.

**Comment by sbordet** [comment]
They are deployed now. Just point your POM to read from that URL and use `4.0.1-SNAPSHOT` as CometD version.

**Comment by nathklei** [comment]
@sbordet thanks, I just got that to resolve (using gradle, but works just the same). The fix seems to work on Undertow now - appreciate the quick response. Can you please cut a 4.0.1? My build system only allows non-snapshot versions.

**Comment by nathklei** [comment]
Hi @sbordet, do you have any updates on when `4.0.1` might be released? Thank you for your help!

**Comment by sbordet** [comment]
@nathklei I am finishing up #726 and after that I will probably cut the release. Hold on for a little longer.

**Comment by nathklei** [comment]
Great, thanks for the update

**Comment by sbordet** [comment]
@nathklei 4.0.1 has been released.

**Comment by nathklei** [comment]
@sbordet thank you!
