### ISSUE TITLE
Depreciate 4.0.4 and release as a new MINOR version instead of a patch.

### ISSUE THREAD

**Issue by ChuckJonas** [cometd/cometd#861]
I'm not sure why yet, but 4.0.4 breaks on import when running under node.  (Where as it used to just break after initializing a new client class)!

/Users/jonas/Documents/code/bass/node_modules/cometd/cometd.js:22
        runtime = window;
        ^

ReferenceError: window is not defined
    at _ids (/Users/jonas/Documents/code/bass/node_modules/cometd/cometd.js:22:9)
    at Object.<anonymous> (/Users/jonas/Documents/code/bass/node_modules/cometd/cometd.js:37:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonas/Documents/code/bass/node_modules/ts-force/build/streaming/stream.js:4:16)

My library was referencing `^4.0.3` and since this was released as a patch, my package's version is getting auto-upgraded to `4.0.4` and now break without being able to do anything (you would need to require `cometd-nodejs-client` before ever loading the cometd module... which I can't do in old versions).

Beyond this potentially breaking other dependent packages, I feel that just the simple act of `requiring()` cometd should NOT throw this exception!

**Comment by ChuckJonas** [comment]
IOW, I think you need to run:

`npm deprecate cometd@4.0.4 "some message"`

and release this as 4.1.0

**Comment by sbordet** [comment]
Released `cometd-nodejs-client@1.0.4` to fix the issue.
