### ISSUE TITLE
LinkageError when using client JettyWebSocketTransport in webapp

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#862]
```
java.lang.LinkageError: loader constraint violation: when resolving method "org.eclipse.jetty.websocket.client.WebSocketClient.getHttpClient()Lorg/eclipse/jetty/client/HttpClient;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/cometd/websocket/client/JettyWebSocketTransport, and the class loader (instance of org/eclipse/jetty/start/Classpath$Loader) for the method's defining class, org/eclipse/jetty/websocket/client/WebSocketClient, have different Class objects for the type org/eclipse/jetty/client/HttpClient used in the signature
        at org.cometd.websocket.client.JettyWebSocketTransport.init(JettyWebSocketTransport.java:71)
        at org.cometd.client.BayeuxClient.prepareTransport(BayeuxClient.java:995)
        at org.cometd.client.BayeuxClient.access$2200(BayeuxClient.java:101)
        at org.cometd.client.BayeuxClient$SessionState.handshaking(BayeuxClient.java:1410)
        at org.cometd.client.BayeuxClient$SessionState.access$3800(BayeuxClient.java:1285)
        at org.cometd.client.BayeuxClient.lambda$handshake$1(BayeuxClient.java:300)
        at org.cometd.client.BayeuxClient$SessionState.process(BayeuxClient.java:1607)
        at org.cometd.client.BayeuxClient$SessionState.submit(BayeuxClient.java:1579)
        at org.cometd.client.BayeuxClient$SessionState.access$500(BayeuxClient.java:1285)
        at org.cometd.client.BayeuxClient.handshake(BayeuxClient.java:300)
```

**Comment by sbordet** [comment]
This was introduced when trying to avoid usage of deprecated methods in 56838072c65ef40490b482d7f57fc4e1750ffb2f.

Unfortunately, the Jetty server has its own copy of `HttpClient` (for use in the WebSocket implementation) so the JVM hits a `LinkageError` if `WebSocketClient`'s `HttpClient` is exposed to a webapp that also has `HttpClient` in `WEB-INF/lib`.
