### ISSUE TITLE
sweep mechanism can be stopped with JVM Bug?

### ISSUE THREAD

**Issue by squiddle** [cometd/cometd#960]
This is a rather weird issue that can be serious (it was for us). It seems to involve a JVM/Hotspot bug, where an exception is not caught in a try/catch block.

I can fully understand if this issue is directly closed.

Let's start with where the problem occured. Sweep is done roughly every second (default sweep period is 997ms). It is implemented with a Runnable that executes the seep and afterwards schedules itself into the future.
```java
schedule(new Runnable() {
    @Override
    public void run() {
        sweep();
        schedule(this, sweepPeriod);
    }
}, sweepPeriod);
```
if `sweep` experiences an uncatched exception in this `#run` method, the call to schedule will not happen. This must happen once during runtime to break sweep. This exception is not going to be logged on typical productive logging configuration (i couldn't manage to find all the details in the jetty scheduler code if and at what level the exception would be logged).

A bandaid for a running system is using the BayeuxMBean to call `sweep` via JMX.

We confirmed the issue by subclassing BayeuxServerImpl and overriding sweep to try/catch and log any exception, eventually it was triggered again. 

Now comes the weird part. All this is on a cometd 5.0.0 codebase.

I post the relevant part of the stacktrace first:
```txt
at org.cometd.server.ServerChannelImpl.notifyUnsubscribed(ServerChannelImpl.java:193)
at org.cometd.server.ServerChannelImpl.unsubscribe(ServerChannelImpl.java:170)
at org.cometd.server.ServerChannelImpl.unsubscribe(ServerChannelImpl.java:150)
at org.cometd.server.ServerSessionImpl.removed(ServerSessionImpl.java:824)
at org.cometd.server.BayeuxServerImpl.removeSession(BayeuxServerImpl.java:525)
at org.cometd.server.BayeuxServerImpl.removeServerSession(BayeuxServerImpl.java:502)
at org.cometd.server.ServerSessionImpl.sweep(ServerSessionImpl.java:180)
at org.cometd.server.BayeuxServerImpl.sweep(BayeuxServerImpl.java:1250)
at org.cometd.server.BayeuxServerImpl$1.run(BayeuxServerImpl.java:147)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

the call before is our code that has thrown the exception. Let's look at ServerChannelImpl.java around line 193

```java
  private void notifyUnsubscribed(SubscriptionListener listener, ServerSession session, ServerChannel channel, ServerMessage message) {
    try {
      listener.unsubscribed(session, channel, message);
    } catch (Throwable x) {
      _logger.info("Exception while invoking listener " + listener, x);
    }
  }
```

Once we found the issue of sweep not being called and once we captured this stacktrace we were quite surprised. The exception in our listener should not be able to escape here, but the stacktrace indicates otherwise. I cannot think of other reasons than a javac or JVM/Hotspot bug. Which is normally a strong accusation.

I wanted to suggest to make the sweep scheduling more robust, but i am unsure. If an error like a disfunctional try/catch can happen due to a JVM bug, any kind of precautionary measure is based on a very squishy foundation.

JVM used is Java 8
```txt
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-linux64) (build 1.8.0_262-b19)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.51-CA-linux64) (build 25.262-b19, mixed mode)
```

**Comment by sbordet** [comment]
It's an easy change to re-schedule in a `finally` block, so that will be done.

Does this happen with other JVMs?

**Comment by squiddle** [comment]
we only experienced it on this particular version, but i am not well versed with these JVM internals so i do not know the circumstances that might even trigger this.
